export const REQUEST = {
  LOGIN: '/login',
  SIGNUP: '/v1/user/join',
  PROJECT: '/v1/project',
  INVITE_PROJECT: '/v1/project/invite',
  REFRESH: '/v1/user/refresh',
  CHECK_VALID_ID: '/v1/user/valid/id',
  CHECK_VALID_EMAIL_CODE: '/v1/email/auth',
  CHANGE_PASSWORD: '/v1/user/update/password',
  FETCH_JOINED_PROJECT: '/v1/project/join-project',
  FETCH_JOINED_USER_PROJECT: '/v1/project/join-user',
  SEND_EMAIL_CODE: '/v1/email/auth/send',
  SEND_EMAIL_FIND_ID: '/v1/user/find/id',
  SEND_EMAIL_FIND_PW: '/v1/user/send/password',
  SHARE_LINK: '/v1/share/link',
  FETCH_USER_INFO: '/v1/user/profile',
  FETCH_TOGGLE_SETTING: '/v1/user/setting/profile',
  UPDATE_TOGGLE_SETTING: '/v1/user/update/notification',
};

export const BOARD_REQUEST = {
  COMMENT: '/v1/post/comment',
  POST: '/v1/post',
  BASIC_POST: '/v1/free',
  NOTICE_POST: '/v1/notice',
  VOTE_POST: '/v1/vote',
  VOTE_OPTION: '/v1/vote/option',
  PEER_REVIEW_POST: '/v1/review',
  MEETING_POST: '/v1/meeting',
};
