export const PATH = {
  HOME: '/',
  LOGIN: '/login',
  DEFAULT: '/default',
  SIGNUP: '/signup',
  FIND_ID: '/help-id',
  FIND_PW: '/help-pw',
  PROJECT: '/project',
  PROJECT_CONTENT: '/project/:projectId',
  BOARD: 'board',
  POST_DETAIL: ':postId',
  SEARCH: 'search',
  GROUP_BOARD: ':groupBoardId',
  SCHEDULE: 'schedule',
  ERROR: '/error',
} as const;
